### ISSUE TITLE
Add settings to Admin manager

### ISSUE THREAD

**Issue by lithos77** [cakemanager/cakephp-settings#1]
How can I add Settings to the manager in Admin area (1.0)?

**Comment by bobmulder** [comment]
Hey @lithos77,

You can easily register or write new settings this way: https://github.com/cakemanager/cakephp-settings#usage

Please let me know if it works ;)

**Comment by lithos77** [comment]
From Docs:
If you are using the CakeManager-Plugin, we will create a default form where you can edit your settings (if the field editable isset to 1). The Settings-Plugin will automatically add a menu-item to the admin-area. If you click the menu-item you will see a list with all editable settings who contains the chosen prefix (or default: App).

> This does not happen but maybe I'm missing something: I must specify the prefix? I used App. I did not added the following code (???)

Configure::write('Settings.Prefixes.Plugin', [
    'alias'  => 'Plugin Name',
    'prefix' => 'Plugin',
]);

**Comment by bobmulder** [comment]
I have done some changes. Sorry. I Will take a look at it This afternoon!

**Comment by lithos77** [comment]
Thanks Bob!

**Comment by bobmulder** [comment]
I have done some research. The way of adding a prefix to the CakeManager has changed from this:

``` php
Configure::write('Settings.Prefixes.Plugin', [
    'alias' => 'Plugin Name',
    'prefix' => 'Plugin',
]);
```

To this:

``` php
Configure::write('Settings.Prefixes.Test', 'Test');
```

Don't forget to register your settings with the `register()` method: https://github.com/cakemanager/cakephp-settings#register

Good luck and please let me know if it's solved ;)

**Comment by lithos77** [comment]
It still does not appear in the backend :(
In bootstrap Plugin::load('Settings');
In AppController: 
use Cake\Cache\Cache;

Setting::register('App.Name', 'Default Value', []);
Configure::write('Settings.Prefixes.App', 'App');

**Comment by bobmulder** [comment]
Please post some code so I can help you...
