### ISSUE TITLE
settings editable by roles

### ISSUE THREAD

**Issue by quasiperfect** [cakemanager/cakephp-settings#13]
hi

thanks a lot for your work on cake plugins

would be nice to extend this to be able to use with your users plugin so some settings can be edited only by some roles

**Comment by bobmulder** [comment]
Hi @quasiperfect,

Thank you for your positive feedback. That motivates to continue the work.

What do you mean exactly with your suggestion?

Greetz,

Bob

**Comment by quasiperfect** [comment]
let's say we have the roles
admin,
editor

app.maintenance => editable only by admin
app.default_article_title => editable by editor and admin

**Comment by bobmulder** [comment]
Ah that way... You could do it yourself with a dirty `if()` and `else()` I guess ;)

**Comment by quasiperfect** [comment]
lol sure if is that simple
i'm investigating cake at this moment so no previous experience :P

thanks for your time
