### ISSUE TITLE
Not found cakephp-settings

### ISSUE THREAD

**Issue by jeffersongoncalves** [cakemanager/cakephp-settings#16]
I'm having trouble with the installation of dependence by the composer.
The mistake is giving not find the cakephp-settings directory.

And I checked the cakephp-plugins.php file and it is with this line:

'Settings' => $baseDir . '/vendor/cakemanager/cakephp-settings/'

And cakemanager checked the folder and is the plugin with the Settings name.

Solution would be in cakephp-plugins.php file:

'Settings' => $baseDir . '/vendor/cakemanager/Settings/'

**Comment by sanflynz** [comment]
I (think?) I'm having the same issue.  When I try and run things eg: the migrations it says that it cant find the cakemanager/cakephp-settings/config/bootstrap.php file, but there IS no cakephp-settings bootstrap file.  The file is in cakemanager/settings/config/bootstrap.php.  

If I edit the cakephp-plugins.php file as @simaostephanie mentions above I can get the migrations to work, however if I ever dumpautoload the cakephp-plugins file reverts, and I'm having issues trying to do things like add controllers
