### ISSUE TITLE
Migration: value & description can't have a default value

### ISSUE THREAD

**Issue by virusvn** [cakemanager/cakephp-settings#18]
[PDOException]                                                                                                                 
  SQLSTATE[42000]: Syntax error or access violation: 1101 BLOB, TEXT, GEOMETRY or JSON column 'value' can't have a default value
  SQLSTATE[42000]: Syntax error or access violation: 1101 BLOB, TEXT, GEOMETRY or JSON column 'description' can't have a default value           

My environment: Mysql 5.7 on OSX Capitan
Because columns 'value' and 'description' is "text", that's why they can't have default value

**Comment by bobmulder** [comment]
What solution would you suggest? Are you able to create a PR with a new migration?

**Comment by virusvn** [comment]
Source code at branch "master" already fixed this. 
The problem only happen with version 1.0.0 installed by composer.

**Comment by bobmulder** [comment]
Fixed: https://github.com/cakemanager/cakephp-settings/releases
