### ISSUE TITLE
Extend settings views

### ISSUE THREAD

**Issue by lithos77** [cakemanager/cakephp-settings#5]
Is it possibile to extend or costumize just like users, roles, and post types in admin area, the Settings index and prefix.ctp?

**Comment by bobmulder** [comment]
Hi @lithos77,

Please can you explain me what you want? Are you using the CakeAdmin plugin? Views can always be overwritten: http://book.cakephp.org/3.0/en/views/themes.html

**Comment by lithos77** [comment]
I just wanted to change the cakemanger-settings views... I'm using Cakemanager. Ok I'll try to override using cakephp default rules.

**Comment by bobmulder** [comment]
At first you should stop using the cakemanager and start using the [CakeAdmin Plugin](https://github.com/cakemanager/cakephp-cakeadmin).
Overriding it's template can be done by adding `prefix.ctp` into your `src/Template/Plugin/Settings/prefix.ctp` I guess...
