### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by vaughany** [cakemanager/cakephp-settings#9]
I might be being daft, but both methods of installation aren't working.

Trying `composer require cakemanager/cakephp-settings` (as seen on packagist) fails with "Your requirements could not be resolved to an installable set of packages." error, and I get the same if I add the appropriate line into my composer.json directly, then `composer update`.

Any ideas what's up?

**Comment by bobmulder** [comment]
Hey @vaughany! Thanks for noticing. Please provide some more info about your environment and the whole composer error...

**Comment by vaughany** [comment]
Oh, rubbish, ignore me, I didn't realise it needed the Utils plugin as a dependency. After installing that, the Settings plugin installs just fine! Sorry for the noise (and sorry for forgetting that I could have used Gitter too).

**Comment by bobmulder** [comment]
Thank you for the update. I suppose that utils is required? In that case we should add it as dependency to the composer.json...
